window.calculatorExpressionCatalog = {
  variables: [
    { label: "@feature", insert: "@feature", description: "The current feature object." },
    { label: "@geometry", insert: "@geometry", description: "The current feature geometry." },
    { label: "@id", insert: "@id", description: "The current feature id." },
    { label: "@layer_name", insert: "@layer_name", description: "The active layer name." },
    { label: "@row_number", insert: "@row_number", description: "1-based row number in the active layer." },
    { label: "@parent", insert: "@parent", description: "The parent feature used during aggregate subexpressions." },
    { label: "@element", insert: "@element", description: "Current array item inside `array_foreach()`." },
    { label: "@index", insert: "@index", description: "Zero-based array index inside `array_foreach()`." },
    { label: "@counter", insert: "@counter", description: "One-based array index inside `array_foreach()`." },
  ],
  groups: [
    {
      name: "Conditional",
      items: [
        {
          label: "IF(condition, yes, no)",
          insert: "if(",
          description: "Evaluates one branch when the condition is true and another when it is false.",
          keywords: ["if", "condition", "branch"],
        },
        {
          label: "CASE WHEN ... END",
          insert: "CASE\n  WHEN  THEN \n  ELSE \nEND",
          description: "QGIS-style multi-branch conditional expression.",
          keywords: ["case", "when", "then", "else"],
        },
        {
          label: "COALESCE(a, b, ...)",
          insert: "coalesce(",
          description: "Returns the first non-null value.",
          keywords: ["null", "fallback"],
        },
        {
          label: "NULLIF(a, b)",
          insert: "nullif(",
          description: "Returns null when both values are equal.",
          keywords: ["null", "compare"],
        },
        {
          label: "IFNULL(value, fallback)",
          insert: "ifnull(",
          description: "Returns the fallback when the first value is null.",
          keywords: ["null", "fallback"],
        },
        {
          label: "TRY(value, fallback)",
          insert: "try(",
          description: "Returns a fallback when evaluating the first expression throws an error.",
          keywords: ["error", "fallback"],
        },
        {
          label: "IS NULL",
          insert: " is null",
          description: "Checks whether a value is null.",
          keywords: ["null", "is"],
        },
      ],
    },
    {
      name: "Math",
      items: [
        { label: "ABS(value)", insert: "abs(", description: "Absolute value.", keywords: ["number", "absolute"] },
        { label: "ROUND(value, places)", insert: "round(", description: "Rounds a number.", keywords: ["round"] },
        { label: "FLOOR(value)", insert: "floor(", description: "Rounds down.", keywords: ["floor"] },
        { label: "CEIL(value)", insert: "ceil(", description: "Rounds up.", keywords: ["ceil"] },
        { label: "SQRT(value)", insert: "sqrt(", description: "Square root.", keywords: ["sqrt"] },
        { label: "LOG(value)", insert: "log(", description: "Natural logarithm.", keywords: ["log"] },
        { label: "EXP(value)", insert: "exp(", description: "Exponential function.", keywords: ["exp"] },
        { label: "MIN(a, b, ...)", insert: "min(", description: "Smallest numeric value.", keywords: ["minimum"] },
        { label: "MAX(a, b, ...)", insert: "max(", description: "Largest numeric value.", keywords: ["maximum"] },
        { label: "CLAMP(min:=0, value:=x, max:=1)", insert: "clamp(", description: "Clamps a value between bounds.", keywords: ["range", "limit"] },
        { label: "SIN(value)", insert: "sin(", description: "Sine of an angle in radians.", keywords: ["trig"] },
        { label: "COS(value)", insert: "cos(", description: "Cosine of an angle in radians.", keywords: ["trig"] },
        { label: "TAN(value)", insert: "tan(", description: "Tangent of an angle in radians.", keywords: ["trig"] },
        { label: "RADIANS(value)", insert: "radians(", description: "Converts degrees to radians.", keywords: ["degrees"] },
        { label: "DEGREES(value)", insert: "degrees(", description: "Converts radians to degrees.", keywords: ["radians"] },
      ],
    },
    {
      name: "String",
      items: [
        { label: "CONCAT(a, b, ...)", insert: "concat(", description: "Joins values together as text.", keywords: ["join", "text"] },
        { label: "a || b", insert: " || ", description: "String concatenation operator.", keywords: ["concat", "operator"] },
        { label: "LOWER(text)", insert: "lower(", description: "Lowercase text.", keywords: ["text"] },
        { label: "UPPER(text)", insert: "upper(", description: "Uppercase text.", keywords: ["text"] },
        { label: "TITLE(text)", insert: "title(", description: "Title-cases text.", keywords: ["text"] },
        { label: "TRIM(text)", insert: "trim(", description: "Removes outer whitespace.", keywords: ["whitespace"] },
        { label: "REPLACE(text, find, with)", insert: "replace(", description: "Replaces matching text.", keywords: ["substitute"] },
        { label: "SUBSTR(text, start, length)", insert: "substr(", description: "Extracts a text slice using 1-based start positions.", keywords: ["slice"] },
        { label: "STRPOS(text, search)", insert: "strpos(", description: "Returns a 1-based match position or 0.", keywords: ["find"] },
        { label: "REGEXP_MATCH(text, pattern)", insert: "regexp_match(", description: "True when the regular expression matches.", keywords: ["regex"] },
        { label: "REGEXP_REPLACE(text, pattern, with)", insert: "regexp_replace(", description: "Regex-based replacement.", keywords: ["regex"] },
      ],
    },
    {
      name: "Conversion",
      items: [
        { label: "TO_INT(value)", insert: "to_int(", description: "Converts a value to an integer.", keywords: ["cast"] },
        { label: "TO_REAL(value)", insert: "to_real(", description: "Converts a value to a floating-point number.", keywords: ["cast"] },
        { label: "TO_STRING(value)", insert: "to_string(", description: "Converts a value to text.", keywords: ["cast"] },
        { label: "TO_BOOL(value)", insert: "to_bool(", description: "Converts a value to a boolean.", keywords: ["cast"] },
      ],
    },
    {
      name: "Date",
      items: [
        { label: "NOW()", insert: "now()", description: "Current local date and time.", keywords: ["date", "time"] },
        { label: "YEAR(date)", insert: "year(", description: "Extracts the year.", keywords: ["date"] },
        { label: "MONTH(date)", insert: "month(", description: "Extracts the month number.", keywords: ["date"] },
        { label: "DAY(date)", insert: "day(", description: "Extracts the day of month.", keywords: ["date"] },
        { label: "AGE(date, reference)", insert: "age(", description: "Returns age in whole days.", keywords: ["date", "difference"] },
        { label: "FORMAT_DATE(date, pattern)", insert: "format_date(", description: "Formats a date using simple yyyy/MM/dd tokens.", keywords: ["date", "format"] },
      ],
    },
    {
      name: "Geometry",
      items: [
        { label: "AREA()", insert: "area()", description: "Area of the current or provided geometry.", keywords: ["polygon"] },
        { label: "LENGTH()", insert: "length()", description: "Length of a geometry, text, or array.", keywords: ["line", "count"] },
        { label: "PERIMETER()", insert: "perimeter()", description: "Polygon perimeter.", keywords: ["polygon"] },
        { label: "X()", insert: "x()", description: "X coordinate for a point or centroid.", keywords: ["coordinate"] },
        { label: "Y()", insert: "y()", description: "Y coordinate for a point or centroid.", keywords: ["coordinate"] },
        { label: "CENTROID()", insert: "centroid()", description: "Centroid point geometry.", keywords: ["center"] },
        { label: "BOUNDS()", insert: "bounds()", description: "Bounding box object for a geometry.", keywords: ["bbox"] },
        { label: "DISTANCE(a, b)", insert: "distance(", description: "Distance between point-like geometries in meters.", keywords: ["measure"] },
        { label: "INTERSECTS(a, b)", insert: "intersects(", description: "True when geometries intersect or overlap.", keywords: ["spatial", "predicate"] },
        { label: "CONTAINS(a, b)", insert: "contains(", description: "True when the first geometry contains the second.", keywords: ["spatial", "predicate"] },
        { label: "WITHIN(a, b)", insert: "within(", description: "True when the first geometry is within the second.", keywords: ["spatial", "predicate"] },
      ],
    },
    {
      name: "Arrays",
      items: [
        { label: "ARRAY(a, b, ...)", insert: "array(", description: "Creates an array.", keywords: ["list"] },
        { label: "ARRAY_LENGTH(array)", insert: "array_length(", description: "Returns the array length.", keywords: ["list", "count"] },
        { label: "ARRAY_GET(array, index)", insert: "array_get(", description: "Reads an item from an array using a zero-based index.", keywords: ["list", "index"] },
        { label: "ARRAY_FOREACH(array, expression)", insert: "array_foreach(", description: "Evaluates an expression for each array item using @element, @index, and @counter.", keywords: ["list", "map"] },
      ],
    },
    {
      name: "Aggregates",
      items: [
        { label: "SUM(expression, filter:=...)", insert: "sum(", description: "Adds values across the current layer or an optional layer argument.", keywords: ["aggregate", "total"] },
        { label: "MEAN(expression)", insert: "mean(", description: "Average across matching features.", keywords: ["aggregate", "average"] },
        { label: "MINIMUM(expression)", insert: "minimum(", description: "Smallest value across matching features.", keywords: ["aggregate"] },
        { label: "MAXIMUM(expression)", insert: "maximum(", description: "Largest value across matching features.", keywords: ["aggregate"] },
        { label: "COUNT(expression, filter:=...)", insert: "count(", description: "Counts matching rows or non-null values.", keywords: ["aggregate"] },
        { label: "COUNT_DISTINCT(expression)", insert: "count_distinct(", description: "Counts distinct non-null values.", keywords: ["aggregate", "unique"] },
        { label: "CONCATENATE(expression, delimiter:=', ')", insert: "concatenate(", description: "Joins text results across features.", keywords: ["aggregate", "string"] },
        { label: "ARRAY_AGG(expression)", insert: "array_agg(", description: "Collects values from matching features into an array.", keywords: ["aggregate", "array"] },
        { label: "AGGREGATE(layer, aggregate, expression, filter:=..., order_by:=...)", insert: "aggregate(", description: "Runs a named aggregate against the current or another loaded layer.", keywords: ["aggregate", "cross-layer"] },
      ],
    },
  ],
  foundation: [
    "literals",
    "field references",
    "variables",
    "operators",
    "named parameters",
    "CASE expressions",
    "comments",
  ],
};
